export const Quote = [
    'Chỉ có 1% lượng nước trên thế giới có thể sử dụng được. 97% lượng nước là biển và 2% còn lại đã bị đóng băng.',
    '78% động vật có vú ở biển có nguy cơ tử vong do tai nạn, chẳng hạn như mắc vào lưới đánh cá.',
    'Lượng túi nilon con người xả vào đại dương hàng năm giết chết khoảng 1.000.000 sinh vật biển.',
    'Khoảng 70% bề mặt trái đất được bao phủ bởi nước, vì thế vai trò của nước đối với sự sống trên trái đất là vô cùng quan trọng.',
    'Tắt nước trong lúc đánh răng giúp cắt giảm 1/2 lượng nước chảy phung phí.',
    'Mỗi tấn giấy tái chế giúp tiết kiệm 238 lít dầu, 4.100 kW năng lượng, cứu 17 cây xanh, cắt giảm 27 kg lượng không khí ô nhiễm.',
    'Vào năm 2017, ước tính số người chết do ô nhiễm là khoảng 9 triệu người mỗi năm, nghĩa là trên thế giới, cứ 6 ca tử vong, có 1 ca là do ô nhiễm.',
    'Hơn 1.300 người ở TP Hồ Chí Minh tử vong mỗi năm gây ra do sự ô nhiễm không khí.',
    'Tại HCM, nồng độ bụi mịn PM2.5 gấp 16,4 lần so với tiêu chuẩn chất lượng không khí hàng năm của WHO.',
    'Mỗi lần mở cửa tủ lạnh, có 30% lượng không khí lạnh bị thất thoát.',
    'Lượng gỗ và giấy con người vất đi hàng năm đủ để sưởi ấm 50.000.000 ngôi nhà trong 20 năm.',
    'Mỗi ngày có 27.000 cây xanh bị đốn hạ để làm giấy… toilet.',
    'Mỗi phút có 40.5 ha rừng nhiệt đới bị đốn hạ.',
    'Mỗi ngày ước tính có khoảng 137 loài sinh vật sống ở rừng nhiệt đới bị tiệt chủng.',
    'Chỉ còn chưa đến 4% diện tích rừng ở Việt Nam cho đến ngày nay.',
    'Giấy chỉ có thể được tái chế tối đa sáu lần. Sau đó, các sợi giấy không còn đủ lực liên kết với nhau nữa.',
    'Chiếm 35% lượng chất thải tại các bãi rác là vật liệu đóng gói (bao bì nhựa, kim loại, giấy…).',
    'Mỗi hộ gia đình xả khoảng 40 kg chất thải nhựa hàng năm.',
    'Mỹ là quốc gia có lượng rác thải hàng năm nhiều nhất thế giới, 720 kg/người/năm. Loại rác thải nhiều nhất trong số đó là dao cạo râu nhựa (2 tỉ cái), khăn giấy (1,5 triệu tấn), tã giấy (12 tỉ cái).',
    '84% lượng rác thải gia đình có thể tái chế.',
    'Một chai thủy tinh mất ít nhất 4.000 năm để phân hủy',
    'Hơn 1/3 năng lượng các loại được con người tiêu thụ tại nhà.',
    'Rút phích sạc khi không dùng giúp giảm đến 95% điện năng bị tiêu hao vô ích.',
    'Một chiếc túi nhựa có thể phân hủy trong khoảng từ 10 đến 1.000 năm, trong khi một chai nước bằng nhựa có thể mất tới 450 năm. Một số loại nhựa, chẳng hạn như PVC, có thể mất tới 1.000 năm để phân hủy.',
    'Các yếu tố ảnh hưởng đến sự phân hủy nhựa bao gồm nhiệt độ, độ ẩm và cường độ tiếp xúc với ánh sáng mặt trời. Nói chung, nhựa bị phân hủy nhanh hơn trong môi trường ấm hơn và ẩm ướt hơn.',
    'Điều quan trọng cần lưu ý là ngay cả khi nhựa bị phân hủy, nó cũng không biến mất hoàn toàn. Nhựa phân hủy thành những mảnh nhỏ hơn được gọi là vi nhựa, có thể tồn tại trong môi trường hàng thế kỷ. Những hạt vi nhựa này có thể được động vật ăn vào và có thể xâm nhập vào chuỗi thức ăn, gây rủi ro cho sức khỏe con người.'
]